server:
  port: 9090
  servlet:
    context-path: /forever-system


# 应用名称
spring:
  mvc:
    pathmatch:
      # 配置文档策略
      matching-strategy: ant-path-matcher
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/forever-admin?characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    # 上传文件配置
    multipart:
      enabled: true
      max-file-size: 3MB        #最大文件限制
      max-request-size: 3MB     #最大请求限制
      file-size-threshold: 5MB  #文件超出此大小写入磁盘缓存
      location: /               #磁盘缓存路径
  # redis 配置
#  redis:
#    host: 127.0.0.1
#    password: '123456'

  #security 配置
  security:
    user:
      name: root
      password: root

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.forever.system.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# jwt token
jwt:
  secret: i'm a lsp

#  #spring security配置
#  security:
#    user:
#      name: admin
#      password: admin
#      roles: admin

#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis-plus:
  mapper-locations: classpath*:com/booker/lsp/mapper/**/*.xml
  #指定Mybatis的实体目录
  type-aliases-package: com.booker.lsp.entity
  #日志显示sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
